# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end
  desc "Deploy a new alpha version to the Google Play"
  lane :deploy_alpha do
    gradle(task: 'bundle', build_type: 'Release')
    upload_to_play_store(track: 'alpha')
    slack(
     message: 'Successfully distributed a new alpha build via CI/CD',
     slack_url: "https://hooks.slack.com/services/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"
    )
  end

  desc "Deploy a new beta version to the Google Play"
    lane :deploy_beta do
      gradle(task: 'bundle', build_type: 'Release')
      upload_to_play_store(track: 'beta')
      slack(
         message: 'Successfully distributed a new beta build via CI/CD',
         slack_url: "https://hooks.slack.com/services/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"
      )
    end

  desc "Deploy a new production version to the Google Play"
    lane :deploy_production do
      gradle(
        task: 'bundle',
        build_type: 'Release'
      )
    upload_to_play_store
    slack(
     message: 'Successfully distributed a new production build with via CI/CD',
     slack_url: "https://hooks.slack.com/services/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"
    )
   end
   def on_error(exception)
      slack(
          message: "Some thing goes wrong while deployment with via CI/CD",
          success: false,
          slack_url: "https://hooks.slack.com/services/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",
          attachment_properties: {
              fields: [
                  {
                      title: "Error message",
                      value: exception.to_s,
                      short: false
                  }
              ]
          }
      )
   end

end